apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: mj
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mandoo2276@naver.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minji-com-tls
  namespace: mj
spec:
  secretName: minji-com-tls
  duration: 2160h #90일
  renewBefore: 360h #15일 전에 갱신
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: server.minji2276.shop
  dnsNames:
  - server.minji2276.shop